on:
  push:
    branches:
      - master
      - staging

jobs:
  DeployStaging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Save Kubeconfig
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: echo "$KUBE_CONFIG" > $GITHUB_WORKSPACE/.kubeconfig

    - name: Deploy to K8s
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/.kubeconfig
      with:
        command: |
          kubectl apply -f $GITHUB_WORKSPACE/deployment/staging-spec.yml

    - name: Smoke Test  
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/.kubeconfig
      with:
        command: |
          kubectl -n www-staging rollout status deployment/blog-staging-ghost

  DeployProd:
    name: Deploy Prod
    needs: [DeployStaging]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Save Kubeconfig
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: echo "$KUBE_CONFIG" > $GITHUB_WORKSPACE/.kubeconfig

    - name: Deploy to K8s
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/.kubeconfig
      with:
        command: |
          kubectl apply -f $GITHUB_WORKSPACE/deployment/prod-spec.yml

    - name: Smoke Test  
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/.kubeconfig
      with:
        command: |
          kubectl -n www-prod rollout status deployment/ghost-sql-prod-mysql