on:
  push:
    branches:
      - master
      - staging

jobs:
  DeployStaging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Save Kubeconfig
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: echo "$KUBE_CONFIG" > $GITHUB_WORKSPACE/.kubeconfig

    - name: Render Spec File
      uses: danielr1996/envsubst-action@1.0.0
      with:
        input: /github/workspace/deployment/staging-spec.yml
        output: /github/workspace/deployment/to-deploy.yml
      env:
        commitSHA: ${{ github.sha }}

    - name: Deploy to K8s
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/.kubeconfig
      with:
        command: |
          cat $GITHUB_WORKSPACE/deployment/to-deploy.yml
          kubectl apply -n www-staging -f $GITHUB_WORKSPACE/deployment/to-deploy.yml

    - name: Smoke Test  
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/.kubeconfig
      with:
        command: |
          kubectl -n www-staging rollout status deployment/blog-staging-ghost

  DeployProd:
    name: Deploy Prod
    needs: [DeployStaging]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Save Kubeconfig
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: echo "$KUBE_CONFIG" > $GITHUB_WORKSPACE/.kubeconfig

    - name: Render Spec File
      uses: danielr1996/envsubst-action@1.0.0
      with:
        input: /github/workspace/deployment/prod-spec.yml
        output: /github/workspace/deployment/to-deploy.yml
      env:
        commitSHA: ${{ github.sha }}

    - name: Deploy to K8s
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/.kubeconfig
      with:
        command: |
          kubectl apply -n www-prod -f $GITHUB_WORKSPACE/deployment/to-deploy.yml

    - name: Smoke Test  
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/.kubeconfig
      with:
        command: |
          kubectl -n www-prod rollout status deployment/blog-prod-ghost